### ISSUE TITLE
The weight  'pcpvt_base.pth' which is trained on Ade20k dataset can't be download.

### ISSUE THREAD

**Issue by nizhenliang** [Meituan-AutoML/Twins#2] opened 2021-05-13 13:57 UTC

**Comment by cxxgtxy** [comment] 2021-05-13 14:49
Thanks!
The checkpoint is lost and we rerun the training. We will upload it ASAP.

**Comment by cxxgtxy** [comment] 2021-05-14 02:45
We already update the checkpoint and log for pcpvt-base.
Please have a look.

**Comment by cxxgtxy** [comment] 2021-05-14 04:34
Since the problem is solved, I close the issue.

**Closed as completed by cxxgtxy** 2021-05-14 04:34 UTC
