### ISSUE TITLE
PCPVT代码问题

### ISSUE THREAD

**Issue by qdd1234** [Meituan-AutoML/Twins#3] opened 2021-05-14 02:27 UTC
您好，论文PCPVT图中，PEG的输出特征是要和PEG输入特征相加，但是在代码中PCPVT中我看怎么没有？
![image](https://user-images.githubusercontent.com/68497831/118211605-f26d1680-b49e-11eb-9616-5fe22467d0a3.png)

**Comment by cxxgtxy** [comment] 2021-05-14 02:39
line-515 in gvt.py
![image](https://user-images.githubusercontent.com/9956912/118213565-ca7eb280-b4a0-11eb-91a8-179492eced88.png)

**Comment by qdd1234** [comment] 2021-05-14 07:04
> line-515 in gvt.py
> ![image](https://user-images.githubusercontent.com/9956912/118213565-ca7eb280-b4a0-11eb-91a8-179492eced88.png)

I find it，Thanks！

**Comment by cxxgtxy** [comment] 2021-05-14 09:26
Welcome. I close the issue since the problem is solved.

**Closed as completed by cxxgtxy** 2021-05-14 09:26 UTC
